version: "3.1"

services:

  shippy-cli-consignment:
    build: ./consignment_cli
    environment:
      MICRO_REGISTRY: "mdns"

  shippy-cli-user:
    build: ./user_cli
    environment:
      MICRO_REGISTRY: "mdns"

  shippy-service-consignment:
    build: ./consignment_service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  shippy-service-vessel:
    build: ./vessel_service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  shippy-service-user:
    build: ./user_service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432